### ISSUE TITLE
Issue with Cloud Function URL error

### ISSUE THREAD

**Issue by tnsankaran** [muffaddal52/Send-Google-Analytics-Hits-to-BigQuery#3]
I have followup the steps in the below link 
https://towardsdatascience.com/send-google-analytics-hit-level-data-to-bigquery-5093e2db481b

I have created all the settings as per your guide. while publishing the content, i got this error and I didn't see this variable is created anywhere. What could be the issue?

![image](https://user-images.githubusercontent.com/60739853/113629215-bc5c9b80-9683-11eb-9e77-8c46e64b34dd.png)

**Comment by muffaddal52** [comment]
Hello,
you need to create a variable in gtm with that name and pass your cloud
function URL in it.

**Comment by tnsankaran** [comment]
HI,
thanks. Can you please help me? any example statement? I have created as below

Custom Task - constant variable and value is cloud function link. (https://us-central1**********)
customTask - custom javascript which has a function with "cloud function URL"

This is as per your guide. Where is the mistake?

**Comment by muffaddal52** [comment]
Can you share the screenshot of the error and the variable that you created
for cloud function?

**Comment by tnsankaran** [comment]
![image](https://user-images.githubusercontent.com/60739853/113671283-c8704980-96d3-11eb-81af-cef9b773f54e.png)
![image](https://user-images.githubusercontent.com/60739853/113671347-daea8300-96d3-11eb-90e6-16556221c0f7.png)

**Comment by tnsankaran** [comment]
error already paste in the first request

**Comment by muffaddal52** [comment]
So the issue is that you name the variable as custom task. Rename it as
Cloud Function URL.
[image: image.png]

**Comment by tnsankaran** [comment]
hah. yes.. The error was disappeared. Thank you.

**Comment by muffaddal52** [comment]
Glad to help.

**Comment by tnsankaran** [comment]
Hi, 
need one more help. how do I test this? I have deployed as you said. But I didn't see any transaction happening. Even in the cloud function dashboard, there is no function invocation. any other way to test this or tool? please help..

thank you

**Comment by muffaddal52** [comment]
Hello,
can try and perform some events in browser with GTM and see network calls
to see if the cloud function is being triggered properly?

**Comment by tnsankaran** [comment]
Do I need to create any trigger in order to execute the script from the variable? or need to link with a tag that wants to track?

However, any hit means that at least one tag should be connected, right? it is a bit confusing because so many tags and triggers are used. any best way to isolate the confusion?

**Comment by tnsankaran** [comment]
I probably missed this part. It gives confusion by its representing way.. I didn't figure out just like that it is a settings other than from the snip you have provided.. let me check this and let you know
![image](https://user-images.githubusercontent.com/60739853/114296441-ffc26a00-9ac8-11eb-8131-b15092392f3b.png)

**Comment by muffaddal52** [comment]
you will have to add custom task trigger in the field settings of you
google analytics setting variable.
here is a custom task guide
https://www.simoahava.com/analytics/customtask-the-guide/

**Comment by tnsankaran** [comment]
I have added the GA settings as per instructions, but I didn't find any response to the data flow. However, the setup was done as per your guide. I don't know where I am standing and set the checkpoint to resolve why this is not working. I have reviewed the simoahava page, It is mentioned how the custom task is works. 

I hope I didn't require to configure any tag items for this because it just captures the hit request arrived at GTM and forward it to cloud function. Is this correct? then the configuration is correct, but don't know where is the checkpoint for the issue scenario? do I need any specific page hit or it takes whatever page hits in order to invoke the function?

**Comment by muffaddal52** [comment]
Yes correct it takes all the hits and forward to cloud function. You will
need to use network tab of console to diagnose if gtm is sending data to
cloud function or not.

**Comment by tnsankaran** [comment]
Hi,
I have tried preview mode, 
Container Loaded: I could see the variables are loaded. But the GA settings values are loaded like this.
![image](https://user-images.githubusercontent.com/60739853/115193352-ae8a2a00-a109-11eb-9c5f-8b1c0af8d613.png)

But I did not see how does this works and how it impact the function triggered to be identified? any idea?

**Comment by muffaddal52** [comment]
Yes that's how it should be.

**Comment by tnsankaran** [comment]
But the function seems did not work.. how do I test that?

**Comment by muffaddal52** [comment]
Did you have a look at network calls in browser console?

**Comment by tnsankaran** [comment]
yes. But I didn't see the custom javascript name is found.

**Comment by muffaddal52** [comment]
In network call diagnose if the hits are being send properly or not. Search
for your cloud function there.

**Comment by tnsankaran** [comment]
No, I haven't seen the function name in the list. don't know where should check this next?

**Comment by muffaddal52** [comment]
In the search bar type function and perform some events.

**Comment by tnsankaran** [comment]
this is what I got under gtm.js

{
      "function":"__c",
      "vtp_value":"https:\/\/us-central1-******/function-1\/"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return function(a){var c=",["escape",["macro",25],8,16],",d=\"_\"+a.get(\"trackingId\")+\"_sendHitTask\",e=window[d]||a.get(\"sendHitTask\");a.set(\"sendHitTask\",function(b){var f=b.get(\"hitPayload\");e(b);jQuery.post(c,{payload:JSON.stringify(f)})})}})();"]
    }

**Comment by tnsankaran** [comment]
did you mean, call the function in the address bar with some events as parameters?

**Comment by tnsankaran** [comment]
I got this issue when call the function

Error: Forbidden
Your client does not have permission to get URL /function-1/ from this server.

**Comment by muffaddal52** [comment]
how did you create the cloud function? change the setting to
un-authenticate.

**Comment by tnsankaran** [comment]
yes. I have changed the permission settings and the error disappeared. Also, checked in the network console and GTM preview mode by performing some link click action. In every event, the variables are loading, but no function has been called. I don't know why..

**Comment by tnsankaran** [comment]
Do I need to setup any tag to trigger this variable?

**Comment by muffaddal52** [comment]
Of course, it will only trigger the cloud function when an event is sent to
GA. So yes setup a tag that sends something to GA.

**Comment by tnsankaran** [comment]
But, I have understood from your blog, it is requested to create in the variable. So I missed that and created it in the variables section. Is that missed in the blog?

**Comment by tnsankaran** [comment]
I have created tag and let me check this..

**Comment by tnsankaran** [comment]
Hi,

I have seen the functions are running. I could see in the spike in the function dashboard. However, the data is not sending to biguquqery. Rather than it is uploaded to cloud storage bucket as json file.

Surprising I did not see much detail information in the file. it is without any dimension values and only some meta information. Not sure it is not as it is mentioned in your blog (no dimension details) 

2 things.. why data did not send to bigquery. why json file has only few information. anything need to change in the configuration?

**Comment by muffaddal52** [comment]
Cloud function sends data to cloud storage only when there is an error in
the code or while doing bigquery insertion.

Try and diagnose the cause. See any error message you see in cloud function
logs.

**Comment by tnsankaran** [comment]
this is the error. is this because of empty object return  or error in the code, not sure.

![image](https://user-images.githubusercontent.com/60739853/115386390-f20e9200-a1f6-11eb-9d0c-015823bc62f4.png)

**Comment by muffaddal52** [comment]
Yes, it is. Unable to insert into bigquery.

**Comment by tnsankaran** [comment]
permission issue?

**Comment by muffaddal52** [comment]
Not sure, could be. You will have to search to see possible solution

**Comment by tnsankaran** [comment]
Hi

I have figured out the issue. It is the problem in adding the timestamp to the payload. it is actually appending inside the payload and payload data moved out. How do I add timestamp additionally as separate column?

**Comment by muffaddal52** [comment]
can you share the code that is replacing the payload as you mentioned?

**Comment by tnsankaran** [comment]
This is the part of full code which adding timestamp to payload and this replace the content.

//check if body is not null of response
  if(req.body!==null){
//storing body as hit variable.`
    var hit = req.body;
//adding the hit timestampe so that we can get data and time of the hit in our data set
    hit['hit_timestamp'] = new Date().getTime();
    
    hit.payload=decodeURIComponent(hit.payload)

**Comment by muffaddal52** [comment]
where does it replace the actual payload?
Here is what code is doing
this is how initial payload looks like

> {
>   'payload': 'GA raw hit here'
> }


this is how the timestamp is added

> {
>   'payload': 'GA raw hit here',
>   'hit_timestamp': '1231233533'
> }

**Comment by tnsankaran** [comment]
you are receiveing data as string in the req.body using JSON.stringfy(). In that you are adding hit_timestamp where there is no array object. I think that is the problem.. You have to send the payload with timestamp to the function as below
`jQuery.post(endpoint, {
        	payload: JSON.stringify(payload),
            hit_timestamp: new Date().getTime()
      });`

In the function side,
` hit.payload=decodeURIComponent(hit.payload)`
`hit.hit_timestamp=decodeURIComponent(hit.hit_timestamp)`
` bigQuery
            .dataset(dataset)
            .table(tableName)
            .insert({
              payload:hit.payload,
              hit_timestamp:hit.hit_timestamp
                })`

payload and timestamp as per the order it created in the bigquery.

**Comment by muffaddal52** [comment]
You mixed two things. the payload that is being sent from GTM is not being
changed in any way. The timestamp is being added to the request variable
and not to the raw hit itself.

Anyhow if your suggestion works for you then go ahead. The intention was to
get you the idea of how to store the GA hits.
